os: linux
dist: bionic

services:
  - docker

language: python
python:
  - '3.8'

script:
  - docker-compose up --detach
  - sleep 10
  - "curl -X POST 'http://localhost:8000/users' -d '{\"username\": \"user\", \"password\": \"pass\"}'"
