os: linux
dist: bionic

language: python
python:
  - '3.8'

services:
  - docker

install:
  - docker run -itd --name tf hashicorp/terraform
  - sudo docker cp tf:/bin/terraform /bin/terraform

script:
  - docker build .
  - cd infra
  - terraform init
  - terraform validate
