version: '3'

services:
  app:
    build: '.'
    ports:
      - '8000:8000'
    environment:
      - 'POSTGRES=postgres://postgres@db'

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
